const x = 10;

try{                                               //Tente...
    x = 2
}catch(err) {                                      //Se n√£o.
    console.log(`Erro: ${err}`)
}
